name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Vim
      uses: rhysd/action-setup-vim@v1
      id: vim
    - name: Install Vader
      uses: actions/checkout@v2
      with:
        repository: junegunn/vader.vim
        path: vader.vim
    - name: Run tests
      env:
        VADER_PATH: vader.vim
      run: |
        vim --version
        cd tests
        ./runtest.sh
